# Generated by Django 4.0.4 on 2022-05-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_body_article_picture_article_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, max_length='500'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(default='', max_length=150),
        ),
    ]
