# Generated by Django 4.0.4 on 2022-05-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='linkedin',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
